apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mongo-secret-csi
spec:
  provider: azure
  parameters:
    clientID: ${AZURE_APP_MSI}
    keyvaultName: ${AZURE_KEY_VAULT_NAME}
    objects: |
      array:
        - |
          objectName: mongodburi
          objectType: secret
    tenantId: ${AZURE_TENANT_ID}
  secretObjects:
  - data:
    - key: MONGODBURI
      objectName: mongodburi
    secretName: mongodburi
    type: Opaque