apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: ratings
      meta.helm.sh/release-namespace: mongodb
    creationTimestamp: "2023-06-03T22:43:45Z"
    generation: 1
    labels:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: ratings
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: mongodb
      helm.sh/chart: mongodb-13.1.2
    name: ratings-mongodb
    namespace: mongodb
    resourceVersion: "11152"
    uid: fffd6624-180f-4a7b-8b2c-3d4daa82315c
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/instance: ratings
        app.kubernetes.io/name: mongodb
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: mongodb
          app.kubernetes.io/instance: ratings
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: mongodb
          helm.sh/chart: mongodb-13.1.2
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: mongodb
                    app.kubernetes.io/instance: ratings
                    app.kubernetes.io/name: mongodb
                namespaces:
                - mongodb
                topologyKey: kubernetes.io/hostname
              weight: 1
        containers:
        - env:
          - name: BITNAMI_DEBUG
            value: "false"
          - name: MONGODB_EXTRA_USERNAMES
            value: mongo
          - name: MONGODB_EXTRA_DATABASES
            value: ratingsdb
          - name: MONGODB_EXTRA_PASSWORDS
            valueFrom:
              secretKeyRef:
                key: mongodb-passwords
                name: ratings-mongodb
          - name: MONGODB_ROOT_USER
            value: root
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mongodb-root-password
                name: ratings-mongodb
          - name: ALLOW_EMPTY_PASSWORD
            value: "no"
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
          - name: MONGODB_DISABLE_SYSTEM_LOG
            value: "no"
          - name: MONGODB_DISABLE_JAVASCRIPT
            value: "no"
          - name: MONGODB_ENABLE_JOURNAL
            value: "yes"
          - name: MONGODB_PORT_NUMBER
            value: "27017"
          - name: MONGODB_ENABLE_IPV6
            value: "no"
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          image: docker.io/bitnami/mongodb:5.0.14-debian-11-r9
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - /bitnami/scripts/ping-mongodb.sh
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 10
          name: mongodb
          ports:
          - containerPort: 27017
            name: mongodb
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bitnami/scripts/readiness-probe.sh
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /bitnami/mongodb
            name: datadir
          - mountPath: /bitnami/scripts
            name: common-scripts
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1001
        serviceAccount: ratings-mongodb
        serviceAccountName: ratings-mongodb
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 360
            name: ratings-mongodb-common-scripts
          name: common-scripts
        - name: datadir
          persistentVolumeClaim:
            claimName: ratings-mongodb
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-06-03T22:44:23Z"
      lastUpdateTime: "2023-06-03T22:44:23Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-06-03T22:43:45Z"
      lastUpdateTime: "2023-06-03T22:44:23Z"
      message: ReplicaSet "ratings-mongodb-757dc99946" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: ratings
      meta.helm.sh/release-namespace: mongodb
    creationTimestamp: "2023-06-03T22:43:45Z"
    labels:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: ratings
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: mongodb
      helm.sh/chart: mongodb-13.1.2
    name: ratings-mongodb
    namespace: mongodb
    resourceVersion: "10956"
    uid: 343a96fb-4ca2-4d63-ad20-a3fda706fd11
  spec:
    clusterIP: 172.10.93.151
    clusterIPs:
    - 172.10.93.151
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: mongodb
    selector:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: ratings
      app.kubernetes.io/name: mongodb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      meta.helm.sh/release-name: ratings
      meta.helm.sh/release-namespace: mongodb
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
      volume.kubernetes.io/selected-node: aks-npuser01-16107864-vmss000000
      volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
    creationTimestamp: "2023-06-03T22:43:45Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: ratings
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: mongodb
      helm.sh/chart: mongodb-13.1.2
    name: ratings-mongodb
    namespace: mongodb
    resourceVersion: "10986"
    uid: 1918f456-708e-45f3-abec-147aeed6b07f
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: default
    volumeMode: Filesystem
    volumeName: pvc-1918f456-708e-45f3-abec-147aeed6b07f
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2023-06-03T22:43:44Z"
    name: default
    namespace: mongodb
    resourceVersion: "10946"
    uid: 8e082de5-0c70-4ce7-9285-dc4a0c1811d3
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: ratings
      meta.helm.sh/release-namespace: mongodb
    creationTimestamp: "2023-06-03T22:43:45Z"
    labels:
      app.kubernetes.io/instance: ratings
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: mongodb
      helm.sh/chart: mongodb-13.1.2
    name: ratings-mongodb
    namespace: mongodb
    resourceVersion: "10950"
    uid: 0b73dadb-7b2e-405b-aa5d-0f70294d2475
  secrets:
  - name: ratings-mongodb
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
