apiVersion: v1
data:
  mongodb-passwords: bW9uZ28=
  mongodb-root-password: bW9uZ28=
kind: Secret
metadata:
  annotations:
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: ratings
    app.kubernetes.io/name: mongodb
  name: ratings-mongodb
  namespace: ratingsapp
type: Opaque
